# Generated by Django 4.1.3 on 2023-02-21 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0016_alter_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='shared_body',
        ),
    ]
