# Generated by Django 4.1.3 on 2023-02-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0017_remove_post_shared_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
